import "./globals.css";
import { Inter } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Nav from "./(components)/nav";
config.autoAddCss = false;
const inter = Inter({ subsets: ["latin"] });
import React from "react";
import { Provider } from "react-redux";
import { store } from "./Store/Store";
export const metadata = {
  title: "Create Tickets App",
  description: "Generated by Sagi Levy",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen max-h-screen">
          <Nav />
          <div className="flex-grow overflow-y-auto bg-page text-default-text">
            <Provider store={store}>
              {/* Render the children components */}
              {children}
            </Provider>
          </div>
        </div>
      </body>
    </html>
  );
}
